name: ci

on:
  push:
    branches: master

jobs:
  export-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: proxmox-backup-server-stable:latest
      -
        name: Inspect
        run: |
          docker image inspect proxmox-backup-server-stable:latest
